LineageOS-20:
  kernel:
    - git clone https://github.com/LineageOS/android_kernel_oneplus_sm8250 --single-branch -b lineage-21 
  clang:
   # - git clone --depth=1 https://gitlab.com/Jprimero15/lolz_clang.git -b main
    - curl https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/961622e926a1b21382dba4dd9fe0e5fb3ee5ab7c.tar.gz -RLO && tar -C clang/ -xf clang-*.tar.gz
   # - wget wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/961622e926a1b21382dba4dd9fe0e5fb3ee5ab7c.tar.gz && tar -C aarch64/ -xf 961622e926a1b21382dba4dd9fe0e5fb3ee5ab7c.tar.gz
  config:
    - make O=out ARCH=arm64 /vendor/kona_defconfig
  build:
   # - ARCH=arm64 CC=clang CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi" CROSS_COMPILE_ARM32="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
     - ARCH=arm64 CC=clang CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-android-" make -j$(nproc --all) CONFIG_SECTION_MISMATCH_WARN_ONLY=y LLVM=1 LLVM_IAS=1 LD=ld.lld AR=llvm-ar NM=llvm-nm AS=llvm-as OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip O=out
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - nashc
  kernelSU:
    - stable-pin
    
Clean:
  out:
    - rm -rf out
  kernel:
    - make mrproper
  custom:
    - git status

# Stable-pin version of KernelSU is used by KernelSU.sh to replace placeholder (kernelsu-version) with the newest stable version from ksu_version.txt
KernelSU:
  version:
    stable-pin:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s kernelsu-version
    stable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
    unstable:
      - curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

AnyKernel3:
  version:
    nashc:
      - git clone https://github.com/HowWof/AnyKernel3.git -b master
    test:
      - echo "Test Success!"
